# This is a basic workflow to help you get started with Actions

name: Bundle building and pushing

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main, master ] # note, this handles both names while the world transitions

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
     
      - name: Setup Porter
        # You may pin to the exact commit or the version.
        # uses: getporter/gh-action@d8539f57d75587d98651fc94de9e7e63abfaf75e
        uses: getporter/gh-action@v0.1.3 # 1.3 is the latest version
        # The following should be uncommented and modified if you need to pull in custom mixins for your bundle
#      - name: Pull in porter mixins
#        run: |
#          porter mixins install kfctl --url https://github.com/squillace/porter-kfctl/releases/download --version v0.1.1

      - name: Login to GitHub Packages OCI Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PASSWORD }} # requires you to have a GH token and place it in a secret "GHCR_PASSWORD"
      - name: Porter publish to ghcr.io 
      # Note the below automatically sets the registry to the local GH registry of the org name. 
      # Currently, for pure gitops reconstructing this runtime setting will require looking at the repository owner of the commit
        run: |
          porter publish --registry ghcr.io/${{ github.repository_owner }} --debug
